In [1]:
# import needed modules
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
# reading the data
dataset = pd.read_csv("Buy_Book.csv")
dataset

    Age Student  Income    Savings Buy Book
0    43      No  median  Excellent      Yes
1    34     Yes    High       Fair      Yes
2    39     Yes  median       Fair      Yes
3    27     Yes     Low       Fair      Yes
4    44      No    High  Excellent      Yes
5    42      No  median       Fair       No
6    24     Yes    High       Fair      Yes
7    41      No  median       Fair      Yes
8    49      No    High       Fair       No
9    32     Yes    High       Fair      Yes
10   45     Yes     Low  Excellent       No
11   34      No  median  Excellent      Yes
12   21     Yes  median  Excellent      Yes
13   43      No  median  Excellent       No
14   28      No    High  Excellent       No
15   27     Yes     Low       Fair      Yes
16   46     Yes     Low  Excellent       No
17   42      No  median  Excellent      Yes
18   35      No  median  Excellent      Yes
19   38     Yes    High  Excellent      Yes
20   25      No  median       Fair       No
21   36      No    High  Excellent      Yes
22   32     Yes    High       High      Yes
23   49      No     Low       Fair       No
24   31     Yes  median       High      Yes

In [4]:
# transform descriptive data to numerical data
for column in dataset.columns:
    if dataset[column].dtype == type(object):
            
        le = LabelEncoder()
        dataset[column] = le.fit_transform(dataset[column])    
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,[-1]].values
x,y

(array([[43,  0,  2,  0],
        [34,  1,  0,  1],
        [39,  1,  2,  1],
        [27,  1,  1,  1],
        [44,  0,  0,  0],
        [42,  0,  2,  1],
        [24,  1,  0,  1],
        [41,  0,  2,  1],
        [49,  0,  0,  1],
        [32,  1,  0,  1],
        [45,  1,  1,  0],
        [34,  0,  2,  0],
        [21,  1,  2,  0],
        [43,  0,  2,  0],
        [28,  0,  0,  0],
        [27,  1,  1,  1],
        [46,  1,  1,  0],
        [42,  0,  2,  0],
        [35,  0,  2,  0],
        [38,  1,  0,  0],
        [25,  0,  2,  1],
        [36,  0,  0,  0],
        [32,  1,  0,  2],
        [49,  0,  1,  1],
        [31,  1,  2,  2]], dtype=int64), array([[1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1]]))

In [6]:
# split the data into training and testing parts
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=0)
x_train,x_test,y_train,y_test

(array([[34,  1,  0,  1],
        [45,  1,  1,  0],
        [43,  0,  2,  0],
        [49,  0,  0,  1],
        [24,  1,  0,  1],
        [35,  0,  2,  0],
        [44,  0,  0,  0],
        [32,  1,  0,  1],
        [41,  0,  2,  1],
        [25,  0,  2,  1],
        [27,  1,  1,  1],
        [43,  0,  2,  0],
        [36,  0,  0,  0],
        [27,  1,  1,  1],
        [21,  1,  2,  0]], dtype=int64), array([[42,  0,  2,  1],
        [39,  1,  2,  1],
        [38,  1,  0,  0],
        [46,  1,  1,  0],
        [34,  0,  2,  0],
        [32,  1,  0,  2],
        [42,  0,  2,  0],
        [31,  1,  2,  2],
        [49,  0,  1,  1],
        [28,  0,  0,  0]], dtype=int64), array([[1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1]]), array([[0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0]]))

In [7]:
# train the model
knn = KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
knn.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [8]:
# predict the values

y_pred = knn.predict(x_test)
    
age = np.array([[55,0,0,0]])
    
buy_pred = knn.predict(age)

print(f"Age predict for data [55,0,0,0] is : {age}")
print(f"Age predict for data whole test set is : {y_pred}")

Age predict for data [55,0,0,0] is : [[55  0  0  0]]
Age predict for data whole test set is : [1 1 1 0 1 1 1 1 0 1]